# RuboCop設定ファイル
# Ruby コード品質管理のための設定

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"
    - "bin/**/*"
    - "node_modules/**/*"

# レイアウト関連
Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*"

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# スタイル関連
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

# メトリクス関連
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "Rakefile"
    - "*.gemspec"

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

# Lint関連
Lint/MissingSuper:
  Enabled: false

# RSpec関連
RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Exclude:
    - "spec/integration/**/*"
